version: "3.9"  # optional since v1.27.0
services:
  client:
    container_name: dashboard
    stdin_open: true
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - "3001:80"
    volumes:
      - ./api/.env:/code/.env
      - ./api/app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
volumes:
  node_modules:
